### ISSUE TITLE
brew install aws-ddbsh fails with cmake fatal errors

### ISSUE THREAD

**Issue by dgrainge4** [awslabs/dynamodb-shell#22]
**Describe the bug**
The goal was to install *aws-ddbsh* on macOs from a pre-built binary as linked from this [article](https://aws.amazon.com/blogs/database/working-with-json-data-in-amazon-dynamodb/)  

**To Reproduce**
1. Log in to macOs 14.7 as a non-root user.
2. Up to date homebrew installation -- homebrew v4.4
3. Run `brew update` --> "Already up-to-date."
4. `brew doctor` --> "Your system is ready to brew."
5. Install AWS brew tap ` brew tap aws/tap`
6. ddbsh install attempt `brew install aws-ddbsh`
7. fatal error occurs "/tmp/aws-ddbsh-20241003-3081-rsvjis/ddbsh/ddbsh/ddbsh.hpp:16:10: fatal error: 'string' file not found
   16 | #include <string>" (screenshot of terminal output follows)

<img width="866" alt="Screenshot 2024-10-03 at 2 23 09 PM" src="https://github.com/user-attachments/assets/20ac0d76-ede8-4759-96a0-4759b3237665">

**Expected behavior**
Successful installation of *ddbsh* package, to be followed by AWS key configuration steps etc.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.7 (23H124)
 - Browser [chrome, firefox]
 - macOs Terminal built-in utility v2.14 (453)  
 - cmake version **3.30.4**
 
**Additional context**
none.

**Comment by rvamz** [comment]
I tried to reproduce this with the latest version of OSX (15) and the same cmake version and I wasn't able to:

```
❯ sw_vers -productVersion
15.0

~
❯ brew update
==> Updating Homebrew...
Already up-to-date.

~
❯ brew doctor
Your system is ready to brew.

~
❯ brew tap aws/tap

~
❯ brew install aws-ddbsh
==> Fetching dependencies for aws/tap/aws-ddbsh: cmake and aws-sdk-cpp
==> Fetching cmake
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.30.4
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/f753ea54b3e26a109755f3343971fbcab85e9944f43fb130a074afed97fcb601--cmake-3.30.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/blobs/sha256:19ddd00b4b6d7cab
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/20acdb4f924f7385a94a11ecfceeaa21346de342ea5b66bf3047808672af088a--cmake--3.30.4.arm64_sequoia.bottle.tar.gz
==> Fetching aws-sdk-cpp
==> Downloading https://ghcr.io/v2/homebrew/core/aws-sdk-cpp/manifests/1.11.405
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/875ac6cbfac5d9dad3d9f61d2c63087bb3d97c2aef70ace29c4a4b6b461a1d95--aws-sdk-cpp-1.11.405.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/aws-sdk-cpp/blobs/sha256:f47c49fa29
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/9f411f338b561d661110593e6b4d84bd668906a4030837a24ce79f1369ca554b--aws-sdk-cpp--1.11.405.arm64_sequoia.bottle.tar.gz
==> Fetching aws/tap/aws-ddbsh
==> Cloning https://github.com/awslabs/dynamodb-shell.git
Updating /Users/roberto/Library/Caches/Homebrew/aws-ddbsh--git
==> Checking out tag v0.8
HEAD is now at 172de29 added support for on-demand throughput limit
HEAD is now at 172de29 added support for on-demand throughput limit
==> Installing aws-ddbsh from aws/tap
==> Installing dependencies for aws/tap/aws-ddbsh: cmake and aws-sdk-cpp
==> Installing aws/tap/aws-ddbsh dependency: cmake
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.30.4
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/f753ea54b3e26a109755f3343971fbcab85e9944f43fb130a074afed97fcb601--cmake-3.30.4.bottle_manifest.json
==> Pouring cmake--3.30.4.arm64_sequoia.bottle.tar.gz
🍺  /opt/homebrew/Cellar/cmake/3.30.4: 3,424 files, 54.7MB
==> Installing aws/tap/aws-ddbsh dependency: aws-sdk-cpp
==> Downloading https://ghcr.io/v2/homebrew/core/aws-sdk-cpp/manifests/1.11.405
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/875ac6cbfac5d9dad3d9f61d2c63087bb3d97c2aef70ace29c4a4b6b461a1d95--aws-sdk-cpp-1.11.405.bottle_manifest.json
==> Pouring aws-sdk-cpp--1.11.405.arm64_sequoia.bottle.tar.gz
🍺  /opt/homebrew/Cellar/aws-sdk-cpp/1.11.405: 64,181 files, 701.8MB
==> Installing aws/tap/aws-ddbsh
==> cmake -S ddbsh -B build
==> cmake --build build
==> cmake --install build
🍺  /opt/homebrew/Cellar/aws-ddbsh/0.8: 7 files, 747.8KB, built in 16 seconds
==> Running `brew cleanup aws-ddbsh`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`). 
```

**Comment by dgrainge4** [comment]
hello @rvamz 

thanks for looking into this.

I have resolved the issue by completely removing old versions of *Xcode command line tools* and installing again at version 16 (I had several older versions installed).

I can now `brew install aws-ddbsh` and you are welcome to close this issue.

David

**Comment by amrith** [comment]
Thank Roberto and David.

On Oct 3, 2024 9:05 PM, David Grainger ***@***.***> wrote:

hello @rvamz<https://github.com/rvamz>

thanks for looking into this.

I have resolved the issue by completely removing old versions of Xcode command line tools and installing again at version 16 (I had several older versions installed).

I can now brew install aws-ddbsh and you are welcome to close this issue.

David
